### ISSUE TITLE
Support for css files

### ISSUE THREAD

**Issue by LeonB** [wiledal/gulp-include#23]
Is there support for css files? The default `application.css` for rails contains this:

``` css
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, vendor/assets/stylesheets,
 * or vendor/assets/stylesheets of plugins, if any, can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the top of the
 * compiled file, but it's generally better to create a new file per style scope.
 *
 *= require_self
 *= require_tree .
 */
```

But this doesn't get processed. When I add my own require rule:

``` css
/*
= require_tree test
*/
```

This gets generated:

``` css
= require_tree test
.color {
    color: red;
}


*/

```

**Comment by ilyagelman** [comment]
+1

**Comment by benfrain** [comment]
Yes, this caught me out too. Was trying to do globbing of CSS like this:

`/* = include sass/_components/*.css */`

Will go forward slash for now, but 'real' CSS syntax support would be fantastic. Thanks for the great plugin :+1:

**Comment by wiledal** [comment]
The new version supports CSS-style comments!
`/*= require css/_components/*.css */`
Should now work.

**Comment by mean-cj** [comment]
Hello Wiledal Thank for your share.

I found error when you gulp-include with gulp-sass
after remove 
                  .pipe(sass({
                            style: 'compressed',
                            loadPath: [ ]
                        }).on("error", gutil.log))
gulp-include is ok

##My Code
```
                        gulp.src(file.path)
                        .pipe(include().on("error", gutil.log))
                        .pipe(sass({
                            style: 'compressed',
                            loadPath: [ ]
                        }).on("error", gutil.log))
                           .pipe(gulp.dest("/path"))
```

```
/*
//=require ../../assets/simplemde/dist/simplemde.min.css
//=require ../../assets/jquery-file-upload/css/jquery.fileupload.css
//=require ../../assets/jquery-file-upload/css/jquery.fileupload-ui.css
//=require ../../css/assets/jquery-file-upload/fileupload.css
//=require ../../assets/bootstrap-tokenfield/dist/css/bootstrap-tokenfield.css
//=require ../../assets/bootstrap-tokenfield/dist/css/tokenfield-typeahead.css
*/
```



##My Error
```
[01:35:32] { [Error: public/.sass/post/dynamic.scss
  435:10  Invalid CSS after "   filter: progid": expected "}", was "ImageTransform...."]
  formatted: 'Error: Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."\n        on line 435 of stdin\n>> \tfilter: progid: DXImageTransform.Microsoft.gradient( startColorstr=\'#ffffff\',\n   ---------^\n',
  message: 'public/.sass/post/dynamic.scss\n  435:10  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."',
  column: 10,
  line: 435,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mpublic/.sass/post/dynamic.scss\u001b[24m\n\u001b[90m  435:10\u001b[39m  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."',
  name: 'Error',
  stack: 'Error: public/.sass/post/dynamic.scss\n  435:10  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."\n    at options.error .../node_modules/gulp-sass/node_modules/node-sass/lib/index.js:277:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
```

Thank you so much.

**Comment by mean-cj** [comment]
Hello wiledal  thank for your share.

I found error with css code, after delete this line is ok.

filter: progid: DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#037db9e8', GradientType=1);

##My Error
```
[01:56:58] { [Error: public/.sass/post/dynamic.scss
  428:11  Invalid CSS after "   filter: progid": expected "}", was "ImageTransform...."]
  formatted: 'Error: Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."\n        on line 428 of stdin\n>> \n   ----------^\n',
  message: 'public/.sass/post/dynamic.scss\n  428:11  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."',
  column: 11,
  line: 428,
  file: 'stdin',
  status: 1,
  messageFormatted: '\u001b[4mpublic/.sass/post/dynamic.scss\u001b[24m\n\u001b[90m  428:11\u001b[39m  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."',
  name: 'Error',
  stack: 'Error: public/.sass/post/dynamic.scss\n  428:11  Invalid CSS after "\tfilter: progid": expected "}", was "ImageTransform...."\n    at options.error (..l/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:277:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }

```
