### ISSUE TITLE
#=require always performs an include

### ISSUE THREAD

**Issue by shadow1runner** [wiledal/gulp-include#46]
Having the following file used for inclusion
```
# basic-include.tcl
#=require   deep_path/b.tcl
#=require   deep_path/b.tcl
```
and `deep_path/b.tcl` looking as follows:
```
# b.tcl
```

leads to the following failing test:
```
1) gulp-include File including should replace special comments with file contents in tcl files:

    AssertionError: expected '# basic-include.tcl\n# b.tcl\n# b.tcl' to equal '# basic-include.tcl\n# b.tcl\n#=require
 deep_path/b.tcl'
    + expected - actual

     # basic-include.tcl
     # b.tcl
    -# b.tcl
    +#=require   deep_path/b.tcl

    at Stream.<anonymous> (E:\temp\gulp-include\test\main.js:41:41)
    at include (E:\temp\gulp-include\index.js:33:7)
    at Context.<anonymous> (E:\temp\gulp-include\test\main.js:44:19)
```

Using other comment styled (`//` or `/*`) works fine though

**Comment by AlexeySmolyakov** [comment]
The same problem.

**Comment by wiledal** [comment]
I have now merged this fix. Thanks!
